"""update product and orders tables

Revision ID: 7be38202d468
Revises: 8506a91c0df7
Create Date: 2025-10-25 00:33:02.291386+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7be38202d468'
down_revision = '8506a91c0df7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('size', sa.String(length=50), nullable=True))
    op.add_column('order_items', sa.Column('color', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('sizes', sa.JSON(), nullable=True))
    op.add_column('products', sa.Column('colors', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'colors')
    op.drop_column('products', 'sizes')
    op.drop_column('order_items', 'color')
    op.drop_column('order_items', 'size')
    # ### end Alembic commands ###
