"""sync models

Revision ID: 81d582d8bc28
Revises: 6774f9dba1b3
Create Date: 2026-01-07 07:46:32.365957+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '81d582d8bc28'
down_revision = '6774f9dba1b3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_surveys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('age', sa.String(), nullable=True),
    sa.Column('profession', sa.String(), nullable=True),
    sa.Column('style', sa.String(), nullable=True),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('hobbies', sa.String(), nullable=True),
    sa.Column('monthly_budget', sa.String(), nullable=True),
    sa.Column('clothing_type', sa.String(), nullable=True),
    sa.Column('suggestions', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_surveys_id'), 'customer_surveys', ['id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('customer_email', sa.String(length=255), nullable=False),
    sa.Column('customer_phone', sa.String(length=50), nullable=True),
    sa.Column('customer_address', sa.Text(), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('size', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_id'), 'order_items', ['id'], unique=False)
    op.add_column('products', sa.Column('stock', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('images', sa.JSON(), nullable=True))
    op.add_column('products', sa.Column('sizes', sa.JSON(), nullable=True))
    op.add_column('products', sa.Column('colors', sa.JSON(), nullable=True))
    op.alter_column('products', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('products', 'category',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('products', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_products_available', table_name='products')
    op.drop_index('idx_products_category', table_name='products')
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.drop_column('products', 'quantity')
    op.drop_column('products', 'contact_name')
    op.drop_column('products', 'image_url')
    op.drop_column('products', 'unit')
    op.drop_column('products', 'contact_phone')
    op.drop_column('products', 'contact_email')
    op.drop_column('products', 'available')
    op.drop_column('products', 'updated_at')
    op.drop_column('products', 'location')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('location', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('available', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('contact_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('contact_phone', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('unit', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('image_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('contact_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('quantity', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.create_index('idx_products_category', 'products', ['category'], unique=False)
    op.create_index('idx_products_available', 'products', ['available'], unique=False)
    op.alter_column('products', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('products', 'category',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('products', 'price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.drop_column('products', 'colors')
    op.drop_column('products', 'sizes')
    op.drop_column('products', 'images')
    op.drop_column('products', 'stock')
    op.drop_index(op.f('ix_order_items_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_customer_surveys_id'), table_name='customer_surveys')
    op.drop_table('customer_surveys')
    # ### end Alembic commands ###
